### ISSUE TITLE
TextEncoder is not defined

### ISSUE THREAD

**Issue by joegasewicz** [cfaester/enzyme-adapter-react-18#1]
```

    ReferenceError: TextEncoder is not defined

      5 | configure({adapter: new Adapter()});

```

Stack:
```
      at node_modules/react-dom/cjs/react-dom-server.browser.development.js:145:19
      at Object.<anonymous> (node_modules/react-dom/cjs/react-dom-server.browser.development.js:7002:5)
      at Object.<anonymous> (node_modules/react-dom/server.browser.js:9:7)
      at Object.<anonymous> (node_modules/@cfaester/enzyme-adapter-react-18/dist/ReactEighteenAdapter.js:11:34)
      at Object.<anonymous> (node_modules/@cfaester/enzyme-adapter-react-18/dist/index.js:6:48)
      at Object.<anonymous> (tests/setupTests.ts:7:49)

```

**Comment by dooman87** [comment]
I had the same issue and this is what solved it for me:

```js
global.TextEncoder = require('util').TextEncoder;
global.TextDecoder = require('util').TextDecoder;
const Adapter = require('@cfaester/enzyme-adapter-react-18').default;

import Enzyme from 'enzyme';

global.URLSearchParams = require('url').URLSearchParams;
Enzyme.configure({adapter: new Adapter()});
```

Using require instead of `import` is important.

**Comment by cfaester** [comment]
Thanks guys. I'll take a quick look.

**Comment by cfaester** [comment]
Hello everyone.
Sorry for getting back so late.

Unfortunately JSDOM appears to have removed Node API's when you activate it, since version 17. This is a problem for us, since we depend on `ReactDOM.renderToStaticMarkup()` to accurately create a render tree for `Enzyme.render()`. I've just pushed a new version instructing a workaround (the aforementioned essentially) if you wish to use `.render()`. 

Ideally I'd want to polyfill this on the fly, but until I find a good method for this, I don't want to leave you hanging without _anything_.

This is available in v0.6.0.

Closed.

**Comment by tbranyen** [comment]
An easy way to backfill this is to do something like:

```
window.TextEncoder = require('util').TextEncoder
```

Somewhere before your code needs it. I put it at the top of my imports in a separate file called `textEncoderPolyfill.js`.

**Comment by DjVreditel** [comment]
This solution didn't work for me, but I've found another one.
Add to the `package.json`:

```json


    "overrides": {
        "enzyme": {
            "cheerio": "1.0.0-rc.12"
        },
    },

```
