### ISSUE TITLE
 Cannot find module 'has'

### ISSUE THREAD

**Issue by Huljo** [cfaester/enzyme-adapter-react-18#9]
Hi, Im trying to configure the Enzyme adapter but when running my jest tests I get the following error: 
`Cannot find module 'has' from '<project_dir>/.yarn/__virtual__/@cfaester-enzyme-adapter-react-18-virtual-66911cc31d/3/.yarn/berry/cache/@cfaester-enzyme-adapter-react-18-npm-0.7.1-f571cd3a5d-10c0.zip/node_modules/@cfaester/enzyme-adapter-react-18/dist'`

I guess this is this import : https://github.com/cfaester/enzyme-adapter-react-18/blob/2fa4ba7c6a84beda763e8dc9e94f2194e2ae6555/src/enzyme-adapter-utils/index.ts#L3C1-L3C1

I can't find the package in this package dependencies and installing `has` on my project do not fix the problem.

I'm using yarn 4.

Any advice?

EDIT: Possibly same issue as https://github.com/cfaester/enzyme-adapter-react-18/issues/3

**Comment by siyadava-sindhu** [comment]
facing same issue that says "has" module not found because of following line of "ReactEighteenAdapter.js"
const has_1 = __importDefault(require("has"));
--> have created following PR to address this issue - https://github.com/cfaester/enzyme-adapter-react-18/pull/11

@Huljo  did you found any other solution for this?

**Comment by cfaester** [comment]
Solved in 0.8.0

**Comment by siyadava-sindhu** [comment]
[like]  Sindhusha Yadavalli reacted to your message:
________________________________
